name: Interface tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  windows-rtools-35:
    runs-on: windows-latest
    name: Windows RTools 3.5
    steps:
    - uses: actions/checkout@v2
      with:  
        submodules: 'recursive'
    - uses: actions/setup-python@v2
      with:
        python-version: '2.x'
    - name: Download & install RTools
      run: |
        Invoke-WebRequest -Uri https://cran.rstudio.com/bin/windows/Rtools/Rtools35.exe -OutFile ./R35.exe
        Start-Process -FilePath ./R35.exe -ArgumentList /VERYSILENT -NoNewWindow -Wait
        echo "C:/Rtools/bin;C:/Rtools/mingw_64/bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
      shell: powershell
    - name: Print toolchain versions and paths
      run: |
        g++ --version
        mingw32-make --version
        Get-Command g++ | Select-Object -ExpandProperty Definition
        Get-Command mingw32-make | Select-Object -ExpandProperty Definition
      shell: powershell
    - name: Build Math libs & add to PATH
      run: |
        mingw32-make -f stan/lib/stan_math/make/standalone math-libs
        echo "D:/a/cmdstan/cmdstan/stan/lib/stan_math/lib/tbb" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
      shell: powershell
    - name: Compile & run the example model
      run: |
        mingw32-make examples/bernoulli/bernoulli.exe
        ./examples/bernoulli/bernoulli.exe sample data file=examples/bernoulli/bernoulli.data.json
      shell: powershell
  mac:
    runs-on: macos-latest
    name: MacOS
    steps:
    - name: Print system info
      run: |
        clang++ --version
        make --version
    - uses: actions/checkout@v2
      with:  
        submodules: 'recursive'
    - uses: actions/setup-python@v2
      with:
        python-version: '2.x'
    - name: Building cmdstan
      run: |
        make -j2 build
    - name: Run interface tests
      run: |
        python runCmdStanTests.py -j2 src/test/interface