name: Manual build test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: something
      run: |
      sudo apt-get install latexmk
      sudo apt-get install texlive-fonts-recommended

    # Runs a single command using the runners shell
    - name: Build manual
      run: make manual

