name: CmdStan tarball builder

'on':
  workflow_dispatch:
    inputs:
      tarball_name: 
        description: 'CmdStan build name'
        required: true
        default: ''
      cmdstan_repo:
        description: 'CmdStan repo'
        required: true
        default: 'stan-dev/cmdstan'
      cmdstan_branch:
          description: 'CmdStan branch'
          required: true
          default: 'develop'
      stan_repo:
        description: 'Stan repo'
        required: true
        default: 'stan-dev/stan'
      stan_branch:
          description: 'Stan branch'
          required: true
          default: 'develop'
      math_repo:
        description: 'Math repo'
        required: true
        default: 'stan-dev/math'
      math_branch:
          description: 'Math branch'
          required: true
          default: 'develop'
      stanc3_repo:
        description: 'Stanc3 repo'
        required: true
        default: 'stan-dev/stanc3'
      stanc3_branch:
          description: 'Stanc3 branch'
          required: true
          default: 'master'
jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam2:alpine-3.9-ocaml-4.07
      options: --user root
    steps:    
      - name: Checkout stanc3
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.stanc3_repo }}
          ref: ${{ github.event.inputs.stanc3_branch }}

      - name: opam caching
        id: opam-cache
        uses: actions/cache@v2
        with:
          path: "~/.opam"
          key: linux-stanc-binary-4.07

      - name: Install dependencies
        run: |
          sudo apk update
          sudo apk add build-base bzip2 git tar curl ca-certificates openssl m4 bash
          opam init --disable-sandboxing -y
          opam switch 4.07.0 || opam switch create 4.07.0
          eval $(opam env)
          opam repo add internet https://opam.ocaml.org
          opam update
          bash -x scripts/install_build_deps.sh

      - name: Build static Linux binaries
        run: |
          eval $(opam env)
          dune subst
          dune build @install --profile static
          mv _build/default/src/stanc/stanc.exe linux-stanc
      
      - name: Upload Linux stanc
        uses: actions/upload-artifact@v2
        with:
          name: linux-stanc
          path: linux-stanc

  windows:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic
      options: --user root
    steps:    
      - name: Checkout stanc3
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.stanc3_repo }}
          ref: ${{ github.event.inputs.stanc3_branch }}

      - name: opam caching
        id: opam-cache
        uses: actions/cache@v2
        with:
          path: "~/.opam"
          key: windows-stanc-binary-4.07

      - name: Install dependencies
        run: |
          apt-get update -qq
          apt-get install -y --no-install-recommends ca-certificates rsync git build-essential m4 sudo \
          unzip pkg-config libpcre3-dev mingw-w64 gcc wget gawk bubblewrap
          wget https://github.com/ocaml/opam/releases/download/2.0.4/opam-2.0.4-x86_64-linux
          sudo install opam-2.0.4-x86_64-linux /usr/local/bin/opam
          opam init --comp 4.02.3 --disable-sandboxing -y
          eval $(opam env)
          opam switch 4.07.0 || opam switch create 4.07.0
          eval $(opam env)
          opam update
          bash -x scripts/install_build_deps_windows.sh
          eval $(opam env)
          opam install -y js_of_ocaml-compiler.3.4.0 js_of_ocaml-ppx.3.4.0 js_of_ocaml.3.4.0

      - name: Build Windows binaries
        run: |
          eval $(opam env)
          dune subst
          dune build -x windows
          mv _build/default.windows/src/stanc/stanc.exe windows-stanc

      - name: Upload Windows stanc
        uses: actions/upload-artifact@v2
        with:
          name: windows-stanc
          path: windows-stanc
  mac:
    runs-on: macOS-latest
    steps:    
      - name: Checkout stanc3
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.stanc3_repo }}
          ref: ${{ github.event.inputs.stanc3_branch }}

      - name: opam caching
        id: opam-cache
        uses: actions/cache@v2
        with:
          path: "~/.opam"
          key: macOS-stanc-binary-4.07

      - name: Install dependencies
        run: |
          brew install gpatch
          brew install opam
          opam init --disable-sandboxing -y
          eval $(opam env)
          opam switch 4.07.0 || opam switch create 4.07.0          
          eval $(opam env)
          bash -x scripts/install_build_deps.sh

      - name: Build MacOS binaries
        run: |
          eval $(opam env)
          dune subst
          dune build @install
          mv _build/default/src/stanc/stanc.exe mac-stanc
      
      - name: Upload MacOS binaries
        uses: actions/upload-artifact@v2
        with:
          name: mac-stanc
          path: mac-stanc
  build:
    needs:  [linux, windows, mac]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-python@v1
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.cmdstan_repo }}
        ref: ${{ github.event.inputs.cmdstan_branch }}
        path: cmdstan

    - uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.stan_repo }}
        ref: ${{ github.event.inputs.stan_branch }}
        path: cmdstan/stan

    - uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.math_repo }}
        ref: ${{ github.event.inputs.math_branch }}
        path: cmdstan/stan/lib/stan_math
    
    # - name: Building
    #   run: |
    #     cd cmdstan
    #     make build
    #     make clean-all
    
    - name: install git-archive-all
      run: |
        pip install git-archive-all

    - name: package tarball
      run: |
        cd cmdstan
        git-archive-all cmdstan-temp.tar.gz
        ls -l
        mkdir cmdstan-${{ github.event.inputs.tarball_name }}
        tar -xvzf cmdstan-temp.tar.gz -C cmdstan-${{ github.event.inputs.tarball_name }}/
        mkdir bins
    
    - name: Download MacOS binaries
      uses: actions/download-artifact@v2
      with:
          name: mac-stanc
          path: bins/mac-stanc

    - name: Download Linux binaries
      uses: actions/download-artifact@v2
      with:
          name: linux-stanc
          path: bins/linux-stanc

    - name: Download Windows binaries
      uses: actions/download-artifact@v2
      with:
          name: windows-stanc
          path: bins/windows-stanc

    - name: package tarball
      run: |
        cd cmdstan
        ls -l
        unzip bins/linux-stanc.zip
        unzip bins/windows-stanc.zip
        unzip bins/mac-stanc.zip
        ls -l
        ls -l bins
        ls -l bins/linux-stanc
        tar -cvzf cmdstan-${{ github.event.inputs.tarball_name }}.tar.gz cmdstan-${{ github.event.inputs.tarball_name }}

    - name: Upload tarball
      uses: actions/upload-artifact@v2
      with:
        name:  cmdstan-${{ github.event.inputs.tarball_name }}
        path: 'cmdstan/cmdstan-${{ github.event.inputs.tarball_name }}.tar.gz'

    
